name: checking
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      - run: make setup
      - run: make test
      - run: make lint

